language: cpp
git:
  depth: false # prevent git describe failure when executing the appbase version.cmake.in
cache: ccache
os: osx
osx_image: xcode10.2
addons:
  homebrew:
    packages:
      # - cmake
      - graphviz
      - libtool
      # - automake
      # - wget
      - gmp
      - llvm@4
      - pkgconfig
      - python
      - python@2
      - doxygen
      - libusb
      - openssl
      - boost
before_install: |
  ./.cicd/travis-before.sh
# DOCKER
# script:
# # - docker build -t eosio/ci:ubuntu-18.04 -f ./.cicd/ubuntu-18.04.dockerfile .
# - docker build -t eosio/producer:ci-ubuntu-18.04 -f ./.cicd/ubuntu-18.04.dockerfile .
# after_success:
# - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# # - docker push eosio/ci:ubuntu-18.04
# - docker push eosio/producer:ci-ubuntu-18.04
# EOSIO
script: |
  ./.cicd/travis-build.sh
after_success:
- echo '##### CHECKPOINT 3'