language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      env: $DOCKER_IMAGE=ubuntu:18.04
    - os: linux
      dist: xenial
      env: $DOCKER_IMAGE=ubuntu:16.04
    - os: osx


install:
  - ./.cicd/install.sh

script: echo "ohai"
