os: linux
dist: xenial
language: cpp
compiler: clang
services:
- docker
before_install:
- echo '##### CHECKPOINT 1'
script:
- echo '##### CHECKPOINT 2'
- docker build -t eos-dev -f ./.cicd/ubuntu-18.04.dockerfile .
after_success:
- echo '##### CHECKPOINT 3'
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker tag eos-dev eosio/ci:ubuntu-18.04
- docker push eosio/ci:ubuntu-18.04