language: cpp
git:
  depth: false # prevent git describe failure when executing the appbase version.cmake.in
cache:
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/.ccache
matrix:
  include:
    - os: linux
      dist: xenial
      services: docker
      env: IMAGE_TAG='ubuntu-18.04'
    - os: linux
      dist: xenial
      services: docker
      env: IMAGE_TAG='ubuntu-16.04'
    - os: linux
      dist: xenial
      services: docker
      env: IMAGE_TAG='amazonlinux-2'
    - os: linux
      dist: xenial
      services: docker
      env: IMAGE_TAG='centos-7'
    - os: osx
      osx_image: xcode10.2
      addons:
        homebrew:
          update: true
          packages:
            - graphviz
            - libtool
            - gmp
            - llvm@4
            - pkgconfig
            - python
            - python@2
            - doxygen
            - libusb
            - openssl
            - boost@1.70
before_cache: |
  ./.cicd/travis-before-cache.sh
before_install: |
  ./.cicd/travis-before-install.sh
# DOCKER
# script:
# # - docker build -t eosio/ci:ubuntu-18.04 -f ./.cicd/ubuntu-18.04.dockerfile .
# - docker build -t eosio/producer:ci-ubuntu-18.04 -f ./.cicd/ubuntu-18.04.dockerfile .
# after_success:
# - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# # - docker push eosio/ci:ubuntu-18.04
# - docker push eosio/producer:ci-ubuntu-18.04
# EOSIO
script: |
  ./.cicd/travis-build.sh
after_success:
- echo '##### CHECKPOINT 3'