language: cpp
git:
  depth: false # prevent git describe failure when executing the appbase version.cmake.in
cache: ccache
matrix:
  include:
    - os: linux
      dist: xenial
      services: docker
      env:
        - IMAGE_TAG='ubuntu-18.04'
    - os: linux
      dist: xenial
      services: docker
      env:
        - IMAGE_TAG='ubuntu-16.04'
    - os: linux
      dist: xenial
      services: docker
      env:
        - IMAGE_TAG='amazonlinux-2'
    - os: linux
      dist: xenial
      services: docker
      env:
        - IMAGE_TAG='centos-7'
    # - os: osx
    #   osx_image: xcode10.2

before_install: |
  echo '##### CHECKPOINT 1'
  echo '===== RESOURCES ====='
  echo "$(getconf _NPROCESSORS_ONLN) CPU cores found."
  if [[ "$(uname)" == Darwin ]]; then top -l 1 -s 0 | grep PhysMem; else vmstat -sSM | grep -i 'memory'; fi
  df -h
  echo '====================='
# DOCKER
# script:
# - echo '##### CHECKPOINT 2'
# # - docker build -t eosio/ci:ubuntu-18.04 -f ./.cicd/ubuntu-18.04.dockerfile .
# - docker build -t eosio/producer:ci-ubuntu-18.04 -f ./.cicd/ubuntu-18.04.dockerfile .
# after_success:
# - echo '##### CHECKPOINT 3'
# - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# # - docker push eosio/ci:ubuntu-18.04
# - docker push eosio/producer:ci-ubuntu-18.04
# EOSIO
script: |
  echo '##### CHECKPOINT 2'
  ./.cicd/travis-build.sh
after_success:
- echo '##### CHECKPOINT 3'