steps:
  - wait

  - label: ":pipeline: Generate Pipeline Steps"
    command:
      - "git clone https://github.com/EOSIO/eos -b conan-poc-v2 --single-branch ."
      - "./.cicd/generate-pipeline.sh > generated-pipeline.yml"
      - "buildkite-agent pipeline upload < generated-pipeline.yml"
      - "buildkite-agent artifact upload generated-pipeline.yml"
    plugins:
      thedyrt/skip-checkout#v0.1.1:
        cd: ~
    agents:
      queue: "automation-basic-builder-fleet"
    timeout: ${TIMEOUT:-10}

  # - label: ":pipeline: Generate Pipeline Steps"
  #   command:
  #     - "./.cicd/generate-pipeline.sh > generated-pipeline.yml"
  #     - "buildkite-agent pipeline upload < generated-pipeline.yml"
  #     - "buildkite-agent artifact upload generated-pipeline.yml"
  #   agents:
  #     queue: "automation-basic-builder-fleet"
  #   timeout: ${TIMEOUT:-10}