dag: true
steps:
  # - wait

  # - label: ":pipeline: Generate Pipeline Steps"
  #   command:
  #     - "./.cicd/generate-pipeline.sh > generated-pipeline.yml"
  #     - "buildkite-agent pipeline upload < generated-pipeline.yml"
  #     - "buildkite-agent artifact upload generated-pipeline.yml"
  #   agents:
  #     queue: "automation-basic-builder-fleet"
  #   timeout: ${TIMEOUT:-10}

  - label: ":ubuntu: Ubuntu 18.04 - Build"
    key: ubuntu-18.04-build
    command:
      - "./.cicd/build.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env:
      IMAGE_TAG: "ubuntu-18.04"
    agents:
      queue: "automation-eks-eos-builder-fleet"
    timeout: 180

  - label: ":ubuntu: Ubuntu 18.04 - Unit Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 18.04 - Build' && tar -xzf build.tar.gz"
      - "./.cicd/test.sh scripts/parallel-test.sh"
    env:
      IMAGE_TAG: "ubuntu-18.04"
    agents:
      queue: "automation-eks-eos-builder-fleet"
    timeout: 30
    depends_on: "ubuntu-18.04-build"


  # - key: test
  #   command:
  #     - "echo 'derp'"
  #   agents:
  #     queue: "automation-eks-eos-builder-fleet"

  # - command:
  #     - "echo 'derp'"
  #   agents:
  #     queue: "automation-eks-eos-builder-fleet"
  #   depends_on: "test"
    