dag: true
steps:
  # - wait

  # - label: ":pipeline: Generate Pipeline Steps"
  #   command:
  #     - "./.cicd/generate-pipeline.sh > generated-pipeline.yml"
  #     - "buildkite-agent pipeline upload < generated-pipeline.yml"
  #     - "buildkite-agent artifact upload generated-pipeline.yml"
  #   agents:
  #     queue: "automation-basic-builder-fleet"
  #   timeout: ${TIMEOUT:-10}

  - key: test
    command:
      - "echo 'derp'"
    agents:
      queue: "automation-eks-eos-builder-fleet"

  - command:
      - "echo 'derp'"
    agents:
      queue: "automation-eks-eos-builder-fleet"
    depends_on: "test"
    