steps:
  - command: |
        echo "New pipeline!" && \
        pwd && \
        ls && \
        cd Docker/builder && \
        docker build -t eosio/builder -t eosio/builder:$BUILDKITE_BRANCH . --build-arg branch=$BUILDKITE_BRANCH && \
        gcloud
    label: "Docker build"
    agents:
      role: "automation-builder-fleet"
      aws:instance-type: "m5d.2xlarge"
    timeout: 300

  - wait
