steps:
  - command: |
        echo "New pipeline!" && \
        pwd && \
        ls && \
        cd eos/Docker && \
        docker build . -t eosio/eos
    label: "Docker build"
    agents:
      - "role=automation-builder-large"
    timeout: 300

  - wait
