steps:
  - command: |
        echo "AUTHENTICATING GOOGLE SERVICE ACCOUNT" && \
        gcloud --quiet auth activate-service-account b1-automation-svc@b1-automation-dev.iam.gserviceaccount.com --key-file=/etc/gcp-service-account.json && \
        docker-credential-gcr configure-docker && \
        echo "BUILDING BUILD IMAGE" && \
        cd Docker/builder && \
        docker build -t eosio/builder:latest -t eosio/builder:$BUILDKITE_BRANCH . --build-arg branch=$BUILDKITE_BRANCH && \
        docker tag eosio/builder:$BUILDKITE_BRANCH gcr.io/b1-automation-dev/eosio/builder:$BUILDKITE_BRANCH && \
        docker image list && \
        docker push gcr.io/b1-automation-dev/eosio/builder:$BUILDKITE_BRANCH
    label: "Docker build"
    agents:
      role: "automation-builder-fleet"
      aws:instance-type: "m5d.2xlarge"
    timeout: 300

  - wait
