steps:
  - command: |
        echo "New pipeline!" && \
        pwd && \
        ls && \
        ls -lah /usr/bin && \
        gcloud --version
    label: "Docker build"
    agents:
      role: "automation-builder-fleet"
      aws:instance-type: "m5d.2xlarge"
    timeout: 300

  - wait
